name: Call NASA API and Save Result

on:
  workflow_dispatch:

jobs:
  nasa-api-call:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Call NASA API
      env:
        NASA_API_TOKEN: ${{ secrets.NASA_API_TOKEN }}
      run: |
        curl -H "Authorization: Bearer $NASA_API_TOKEN" "https://api.nasa.gov/planetary/apod?api_key=$NASA_API_TOKEN" -o nasa_response.json

    - name: Upload NASA API Response
      uses: actions/upload-artifact@v4
      with:
        name: nasa-api-response
        path: nasa_response.json
