name: Call NASA API

on:
  workflow_dispatch:

jobs:
  nasa-api-call:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Call NASA API
      env:
        NASA_API_TOKEN: ${{ secrets.NASA_API_TOKEN }}
      run: |
        curl -H "Authorization: Bearer $NASA_API_TOKEN" "https://api.nasa.gov/planetary/apod?api_key=$NASA_API_TOKEN"
